# Not need now actually
scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  dof1_position_controller:
    type: effort_controllers/JointPositionController
    joint: dof1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  dof2_position_controller:
    type: effort_controllers/JointPositionController
    joint: dof2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  dof3_position_controller:
    type: effort_controllers/JointPositionController
    joint: dof3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0} #{p: 1.0, i: 1.0, d: 0.0}
